name: Build ProximityDisabler

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: macos-15   # 使用较新的 macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ldid xz coreutils
          sudo mkdir -p /opt/theos
          sudo chown -R $(whoami) /opt/theos

      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git /opt/theos

      - name: Setup Theos Environment
        run: |
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
          echo "PATH=/opt/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          ls -la
          make clean || true
          make package FINALPACKAGE=1

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: ProximityDisabler
          path: packages/*.deb
